title: Abhi Hanchate
logo: /assets/headshot.png
description: >
  <h4>🎯 "The future of manufacturing lies in the seamless integration of data, AI, and human ingenuity."</h2>
  <p><strong> – and I’m dedicated to making that future a reality.</strong></p>
  <p><strong>Recognized as one of “SME’s 30 Under 30”</strong>, I drive innovation in AI-driven smart manufacturing.</p>
  <p>With experience across <strong>industry and research collaborations</strong>, I transform traditional machinery into 
  <strong>secure, intelligent systems</strong> by integrating <strong>IIoT sensors, advanced sensing schemes, and manufacturing cybersecurity.</strong></p>
theme: jekyll-theme-minimal
